### ISSUE TITLE
Layout changes and fonts go crazy

### ISSUE THREAD

**Issue by jolappi** [poptins/craftcms-poptin-app#1]
Installed poptin and everything smooth and fine. 
but when web page was opened it looked like it got messed up and there was error in console 
TypeError: $('#back-to-top').tooltip is not a function. (In '$('#back-to-top').tooltip('show')', '$('#back-to-top').tooltip' is undefined)   (dont know if this is directly responsible for layout mess and fonts missing)

Somewhere in web was suggestion to move jquery libs up but ours are already almost at the top.

Anyway we cannot use this plugin as it is.
Any fix you could come up with would appreciated.

Thanks, Jouni

ps.
This is what the page looked after the plugin installation
<img width="1398" alt="Screenshot 2020-10-23 at 5 53 55" src="https://user-images.githubusercontent.com/1811895/96951361-fcc0c680-14f4-11eb-8eca-2ea2eb9282a2.png">

and this what it actually looks like
<img width="1382" alt="Screenshot 2020-10-23 at 5 54 10" src="https://user-images.githubusercontent.com/1811895/96951385-0ea26980-14f5-11eb-8b3d-b7c138851658.png">

**Comment by poptins** [comment]
Hi :)
Thanks for the feedback! 
Have a look here: https://help.poptin.com/article/show/81098-jquery-conflict-how-to-fix

By the way, our support is available via our live chat inside your Poptin account, and via email - contact@poptin.com

**Comment by jolappi** [comment]
Seems that no matter where we put any of those suggested script lines the layout still changes.
Also getting rid of tooltip error doesn't change the situation, layout still gets messed up.
Could it be some other file poptin plugin loads?

Were loading jquery.touchswipe and jquery.ui and jquery without the plugin and every thing works ok.
but your plugin is also loading jquery.fileupload, jquery.payment,jquery.mobile-events could it be that one of those breaks
normal craft functionality?

**Comment by jolappi** [comment]
Hi.
I tracked the problem to a single file and it is craft.css created by your plugin.
So, in brief, your plugin creates folder to cpresources which has many folders and inside css folder is craft.css which overwrites our own css.
Probably the plugin won't work correctly if we just remove the css created by plugin.
Any fix or work around for this?

**Comment by jolappi** [comment]
And to add to that your plugin uses jquery.fileupload.js which is different what we use and it gives the error mentioned in my first comment.

**Comment by rohan0793** [comment]
Greetings, this issue was fixed in this commit -> https://github.com/poptins/craftcms-poptin-app/commit/b97e049b8a72b6d069cdbe3c3e96f70b83ad9e16

Please try updating our plugin to 1.4.0 (should be available soon in the Craft Plugin Store)

If you still have further issues using the plugin, please feel free to open a new ticket here on github or by contacting our support via live chat inside your poptin account. We are also available at contact@poptin.com.

**Comment by rohan0793** [comment]
Hi @jolappi how are you doing? Just a quick follow up to check if you still have the above mentioned issues? Or were they resolved and you are able to use Poptin now without problems. In case you still have issues, please give the URL to your craft cms website so I can inspect more. Have a good day. :)

**Comment by jolappi** [comment]
Seems that 1.4.0 release fixed those issues.
Thanks.

**Comment by rohan0793** [comment]
Happy to be of service. Please feel free to contact our support anytime for queries at contact@poptin.com. :)
