### ISSUE TITLE
pixel.js returning 404 error

### ISSUE THREAD

**Issue by smalomo** [poptins/craftcms-poptin-app#6]
Using v1.15.0 and Craft v3.8.9 (recently upgraded from v1.4 / Craft 3.6 and noticed that the Poptin plugin stoped working. In the console I see pixel.js is returning a 404 error. It looks like the the plugin should be using a CDN URL but the code is still looking for a local URL. I can see in the database that the poptin_url should be set to app.popt.in 

![Screenshot 2023-06-13 at 8 42 47 AM](https://github.com/poptins/craftcms-poptin-app/assets/2349287/f23f628a-7513-445b-b5b9-bc2991763c06)

![Screenshot 2023-06-13 at 8 38 33 AM](https://github.com/poptins/craftcms-poptin-app/assets/2349287/5b619cb0-4e47-4b82-9751-f6dfe3fefd9a)

**Comment by rohan0793** [comment]
Hi, we will check this issue soon. In the meanwhile, does uninstalling and installing back the Poptin app help? Could you try please? :)

**Comment by smalomo** [comment]
Thank you @rohan0793  - I will try uninstalling and reinstalling. In the meantime, I rolled back to v 1.11.0 and that seems to have resolve the `404` error as it's using the local pixel.js file.

**Comment by rohan0793** [comment]
Hi @smalomo, we tried in our Craft 3 installation as well, and we are able to install Poptin and popups appear with no problem. Are you still facing an issue?

From your screenshot, it seems the client_id was missing, I would still recommend uninstalling/reinstalling Poptin from the marketplace

Please let me know if I can help you debug this further and solve any issues you are still facing :)

![image](https://github.com/poptins/craftcms-poptin-app/assets/6614305/77c6236f-21e4-4053-a9e7-6f4437e5f97b)
