### ISSUE TITLE
Craft 5 compatibility?

### ISSUE THREAD

**Issue by smalomo** [poptins/craftcms-poptin-app#7]
Are there plans to make this plugin compatible with Craft 5?

**Comment by rohan0793** [comment]
Greetings,

It's in our backlog, we will get it to after a while. Sorry for the inconvenience.

In the meanwhile, you can still create a normal Poptin account and add the script manually to your craft 5 app.

Always grateful,
Rohan Chhabra 
Lead Backend Developer 
Poptin

**Comment by smalomo** [comment]
Thanks for confirming!

**Comment by adrum** [comment]
Any update on this?
